# Generated by Django 5.2.6 on 2025-10-21 12:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer', models.CharField(default='Linak', max_length=255)),
                ('current_height', models.FloatField(default=75.0)),
                ('min_height', models.FloatField(default=60.0)),
                ('max_height', models.FloatField(default=120.0)),
                ('current_status', models.CharField(choices=[('idle', 'Idle'), ('moving', 'Moving'), ('error', 'Error'), ('maintenance', 'Maintenance'), ('available', 'Available')], default='available', max_length=50)),
                ('wifi2ble_id', models.CharField(blank=True, max_length=100, null=True)),
                ('api_endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('error_timestamp', models.DateTimeField(blank=True, null=True)),
                ('total_activations', models.IntegerField(default=0)),
                ('sit_stand_counter', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_desk', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeskUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('sitting_time', models.IntegerField(default=0)),
                ('standing_time', models.IntegerField(default=0)),
                ('position_changes', models.IntegerField(default=0)),
                ('average_height', models.FloatField(blank=True, null=True)),
                ('min_height_used', models.FloatField(blank=True, null=True)),
                ('max_height_used', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='web', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='core.desk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Error')], default='offline', max_length=20)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('has_temperature_sensor', models.BooleanField(default=False)),
                ('has_light_sensor', models.BooleanField(default=False)),
                ('has_led_display', models.BooleanField(default=False)),
                ('has_buzzer', models.BooleanField(default=False)),
                ('has_led_indicator', models.BooleanField(default=False)),
                ('firmware_version', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pico', to='core.desk')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=50)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_reservations', to=settings.AUTH_USER_MODEL)),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.desk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('light_level', models.IntegerField(blank=True, null=True)),
                ('led_color_status', models.CharField(blank=True, max_length=50, null=True)),
                ('person_present', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pico_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='core.pico')),
            ],
        ),
        migrations.CreateModel(
            name='UserDeskPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitting_height', models.FloatField(default=72.0)),
                ('standing_height', models.FloatField(default=110.0)),
                ('custom_height_1', models.FloatField(blank=True, null=True)),
                ('custom_height_2', models.FloatField(blank=True, null=True)),
                ('custom_height_1_name', models.CharField(blank=True, max_length=50, null=True)),
                ('custom_height_2_name', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_interval', models.IntegerField(default=30)),
                ('enable_reminders', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='core.desk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desk_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Desk Preference',
                'verbose_name_plural': 'User Desk Preferences',
                'unique_together': {('user', 'desk')},
            },
        ),
    ]
