# Generated by Django 5.2.6 on 2025-11-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_useraccount_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='department',
            field=models.CharField(blank=True, choices=[('Engineering', 'Engineering'), ('Design', 'Design'), ('Marketing', 'Marketing'), ('HR', 'HR'), ('Finance', 'Finance')], max_length=50, null=True),
        ),
    ]
