# Generated by Django 5.2.6 on 2025-11-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_useraccount_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='deskusagelog',
            name='last_height_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
