# Generated by Django 5.2.6 on 2025-12-01 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_complaint'),
        ('core', '0006_desklog_deskreport'),
    ]

    operations = [
    ]
