# Generated by Django 5.2.6 on 2025-12-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_0006_complaint_0006_desklog_deskreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='deskreport',
            name='category',
            field=models.CharField(choices=[('desk_doesnt_move', "Desk doesn't move"), ('desk_uncleaned', 'Desk uncleaned'), ('desk_is_broken', 'Desk is broken'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
