# Generated by Django 4.2.26 on 2025-12-10 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_deskreport_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeskSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('weekdays', models.JSONField(default=list)),
                ('target_height', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_executed', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Desk Schedule',
                'verbose_name_plural': 'Desk Schedules',
                'ordering': ['time'],
            },
        ),
    ]
