# Generated by Django 5.2.6 on 2025-12-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_deskreport_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdeskpreference',
            name='custom_height_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdeskpreference',
            name='custom_height_3_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
