# Generated by Django 5.2.6 on 2025-12-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_deskreport_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
