# Generated by Django 5.2.6 on 2025-12-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_complaint'),
        ('core', '0009_deskschedule'),
    ]

    operations = [
    ]
