# Generated by Django 5.2.6 on 2025-12-11 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_0009_delete_complaint_0009_deskschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SensorReading',
        ),
    ]
