# Generated by Django 5.2.6 on 2025-12-11 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userdeskpreference_custom_height_3_and_more'),
        ('core', '0011_delete_sensorreading'),
    ]

    operations = [
    ]
