# Generated by Django 5.2.6 on 2025-12-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20251211_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdeskpreference',
            name='posture_sitting_duration',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='userdeskpreference',
            name='posture_standing_duration',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='userdeskpreference',
            name='posture_automatic_movement',
            field=models.BooleanField(default=False),
        ),
    ]

