# Generated by Django 5.2.6 on 2025-12-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_userdeskpreference_posture_cycle_preferences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdeskpreference',
            old_name='enable_reminders',
            new_name='enable_posture_cycles',
        ),
        migrations.RemoveField(
            model_name='userdeskpreference',
            name='preferred_interval',
        ),
    ]

